<?php

namespace App\Services;

use App\Support\FaultSimulation;
use App\Support\Idempotency;
use App\Support\RevenueMath;
use Illuminate\Support\Facades\DB;

class ExpectedTotalsService
{
    public const AUTO_NOTE = 'Auto-generated expected total for locations-feed simulation';

    public function ensureForLocationDate(string $locationId, string $reportDate): bool
    {
        $date = substr($reportDate, 0, 10);

        $existing = DB::table('expected_totals')
            ->where('location_id', $locationId)
            ->where('report_date', $date)
            ->first();

        if ($existing !== null && ! $this->isAutoGenerated($existing)) {
            return false;
        }

        return $this->upsertSimulatedExpected($locationId, $date);
    }

    /** @return array{inserted: int, recomputed: int} */
    public function syncFromRevenue(bool $recompute = true): array
    {
        $pairs = DB::table('revenue_records as rr')
            ->join('machines as m', 'm.machine_id', '=', 'rr.machine_id')
            ->select('m.location_id', 'rr.report_date')
            ->distinct()
            ->orderBy('m.location_id')
            ->orderBy('rr.report_date')
            ->get();

        $inserted = 0;
        $refreshed = 0;
        foreach ($pairs as $pair) {
            $locationId = (string) $pair->location_id;
            $reportDate = substr((string) $pair->report_date, 0, 10);
            $existing = DB::table('expected_totals')
                ->where('location_id', $locationId)
                ->where('report_date', $reportDate)
                ->first();

            if ($existing === null) {
                if ($this->upsertSimulatedExpected($locationId, $reportDate)) {
                    $inserted++;
                }

                continue;
            }

            if ($this->isAutoGenerated($existing) && $this->upsertSimulatedExpected($locationId, $reportDate)) {
                $refreshed++;
            }
        }

        if ($recompute) {
            app(ReconcileService::class)->recomputeAllReconciliation();
        }

        return [
            'inserted' => $inserted,
            'refreshed' => $refreshed,
            'recomputed' => (int) DB::table('reconciliation_results')->count(),
        ];
    }

    private function upsertSimulatedExpected(string $locationId, string $reportDate): bool
    {
        $expected = $this->computeCleanExpected($locationId, $reportDate);
        if ($expected === null) {
            return false;
        }

        DB::table('expected_totals')->updateOrInsert(
            ['location_id' => $locationId, 'report_date' => $reportDate],
            [
                'expected_net_revenue' => $expected,
                'notes' => self::AUTO_NOTE,
            ],
        );

        return true;
    }

    private function isAutoGenerated(object $row): bool
    {
        return str_contains((string) ($row->notes ?? ''), self::AUTO_NOTE);
    }

    public function seedReferenceExpectedTotalsIfEmpty(): int
    {
        if (DB::table('expected_totals')->exists()) {
            return 0;
        }

        $path = database_path('sql/reference_data.sql');
        if (! is_readable($path)) {
            return 0;
        }

        $sql = (string) file_get_contents($path);
        if (! preg_match('/INSERT INTO expected_totals\b.*?;/s', $sql, $match)) {
            return 0;
        }

        DB::unprepared($match[0]);

        return (int) DB::table('expected_totals')->count();
    }

    public function computeCleanExpected(string $locationId, string $reportDate): ?float
    {
        $machines = DB::table('machines')
            ->where('location_id', $locationId)
            ->orderBy('machine_id')
            ->pluck('machine_id');

        if ($machines->isEmpty()) {
            return null;
        }

        $rng = Idempotency::seededRngForLocationDate(
            $locationId,
            substr($reportDate, 0, 10),
            (int) env('SEED_RANDOM', 42),
        );

        $total = 0.0;
        foreach ($machines as $machineId) {
            unset($machineId);
            $total += $this->cleanNetForMachine($rng);
        }

        return RevenueMath::round2($total);
    }

    /** @param callable(): float $rng */
    private function cleanNetForMachine(callable $rng): float
    {
        $cashIn = RevenueMath::round2(200 + $rng() * 3300);
        $voucherIn = RevenueMath::round2($rng() * 700);
        $voucherOut = RevenueMath::round2($rng() * 1100);
        $net = RevenueMath::round2($cashIn + $voucherIn - $voucherOut);
        FaultSimulation::pickFaultMode($rng);

        return $net;
    }
}
